export const FETCH_JOBS_START = "FETCH_JOBS_START";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAIL = "FETCH_JOBS_FAIL";

export const USER_SIGNUP_START = "USER_SIGNUP_START";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_RELOAD_SUCCESS = "USER_RELOAD_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const APPLY_TO_JOB_START = "APPLY_TO_JOB_START";
export const APPLY_TO_JOB_SUCCESS = "APPLY_TO_JOB_SUCCESS";
export const APPLY_TO_JOB_FAIL = "APPLY_TO_JOB_FAIL";
